language: rust

dist: xenial

rust:
  - stable
  - beta
  - nightly

os:
  - linux

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-9
      - libtiff-dev
      - libsqlite3-dev

compiler:
  - g++-9

# by default, test vanilla setup on all three channels
env:
  global:
    - PROJ_FEATURES=""

# test both features on Linux stable, but only pkg_config on macOS stable
jobs:
  include:
    - os: linux
      env: CC=gcc-9 CXX=g++-9 CXXFLAGS=-std=c++11 VERBOSE=1 PROJ_FEATURES="--features bundled_proj" RUSTFLAGS="-C default-linker-libraries"
    - os: linux
      env: PROJ_FEATURES="--features pkg_config"
    - os: osx
      osx_image: xcode11.4
      env: PROJ_FEATURES="--features pkg_config"
    - os: osx
      osx_image: xcode11.4
      env: PROJ_FEATURES="--features bundled_proj"

before_install:
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ]  && [ "$PROJ_FEATURES" != "--features bundled_proj" ]; then
      sudo apt-get update
      sudo apt-get -y install pkg-config
      wget https://download.osgeo.org/proj/proj-7.0.1.tar.gz
      tar -xzvf proj-7.0.1.tar.gz
      pushd proj-7.0.1 && ./configure --prefix=/usr && make && sudo make install && popd
    fi
  - |
    if [ "$TRAVIS_OS_NAME" == "osx" ]  && [ "$PROJ_FEATURES" != "--features bundled_proj" ]; then
      brew update
      brew upgrade pkg-config
      brew upgrade proj
    fi

script:
  - echo $CXX
  - which g++
  - g++ -v
  - which ld
  - ld -v
  - g++ -dM -E -x c++  /dev/null | grep -F __cplusplus
  - cargo test -vv $PROJ_FEATURES

cache: cargo
